version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
